# Generated by Django 4.0.5 on 2022-06-05 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('book_cover', models.ImageField(upload_to='images')),
                ('Autor', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
                ('pages', models.IntegerField()),
            ],
        ),
    ]
